apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cartstore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    #value: localhost:6378 # ローカル環境用
    value: redis:6379  # Docker Compose 用
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "false"
  - name: ttlInSeconds
    value: "36000" # 10h
  - name: databaseIndex
    value: "2"
